admin:
  username:  admin_username
  full_name: gecos field
  password:  admin_password
  hash_salt: hash_salt_16_char
  pubkey:    ssh-rsa pubkey_content

centurylink:
  pppoe_username: username@qwest.net
  pppoe_password: pppoe_password

dyndns:
  hostname: dyndns.hostname.example.com
  url:      https://some_lambda_url.lambda-url.us-east-1.on.aws/
  username: dyndns_username
  password: dyndns_password

port_forwards:
  - description: https
    src_port:    443
    dest_ip:     192.168.1.100
    dest_port:   443
    protocol:    tcp

static_dhcp:
  my_host:
    mac: 00:00:00:00:00:00
    ip:  192.168.1.1
    dns:
      - my-host.lan

dns:
  my_other_host:
    ip: 192.168.1.100
    dns:
      - my-other-host.lan

wireguard_peers:
  my-vpn-peer:
    pubkey: wireguard_pubkey
    ip:     10.0.0.1
