---

- name: start syncthing container
  docker_container:
    name:  syncthing
    image: "syncthing/syncthing:{{ syncthing_version }}"
    state: started
    restart_policy: unless-stopped
    env:
      PUID: "{{ syncthing_uid }}"
      PGID: "{{ syncthing_gid }}"
    ports:
      - "127.0.0.1:{{ syncthing_gui_port }}:{{ syncthing_gui_port }}"
      - "{{ syncthing_port }}:{{ syncthing_port }}"
    volumes:
      - "/srv/data/syncthing:/var/syncthing"
