---

- name: Run EBS volume tasks
  import_tasks: ebs_volume.yml

- name: Run Docker configuration tasks
  import_tasks: docker.yml

- name: Start backup service
  service:
    name: backup.service
    state: started
