---

- name: configure aqgo
  copy:
    dest:  /etc/aqgo.conf
    owner: root
    group: root
    mode:  0400
    content: |
      AWS_DEFAULT_REGION=us-east-1
      AWS_ACCESS_KEY_ID={{ lookup('aws_ssm', '/prod/air_quality/aws_iam_access_key_id') }}
      AWS_SECRET_ACCESS_KEY={{ lookup('aws_ssm', '/prod/air_quality/aws_iam_secret_access_key') }}
  tags: [air-quality]
  register: aqgo_config

- name: configure aqgo systemd service
  copy:
    dest:  /etc/systemd/system/aqgo.service
    owner: root
    group: root
    mode:  0444
    content: |
      [Unit]
      Description=Air Quality Daemon
      After=network.target

      [Service]
      ExecStart=/usr/local/bin/aqgo -serial-device-path {{ air_quality_dev_path }} -metric-namespace {{ air_quality_metric_namespace }}
      Type=simple
      Restart=always
      RestartSec=30
      TimeoutStopSec=2
      EnvironmentFile=/etc/aqgo.conf

      [Install]
      WantedBy=multi-user.target
  tags: [air-quality]

- name: reload systemd configuration
  systemd:
    daemon_reload: yes
  tags: [air-quality]

- name: enable, (re)start aqgo
  systemd:
    name:    aqgo
    state:   "{{ 'restarted' if (aqgo_config.changed) else 'started' }}"
    enabled: yes
  tags: [air-quality]
