---

- name: deploy backup script
  copy:
    src:   backup/backup
    dest:  /usr/local/bin/backup
    owner: root
    group: root
    mode:  0755
  tags: [backup]

- name: create backup script config directory
  file:
    path:  /etc/backup
    state: directory
    owner: root
    group: root
    mode:  0755
  tags: [backup]

- name: deploy backup script env config
  template:
    src:   backup/env.conf.j2
    dest:  /etc/backup/env.conf
    owner: root
    group: root
    mode:  0400
  tags: [backup]

- name: deploy backup script syncthing config
  template:
    src:   backup/syncthing.conf.j2
    dest:  /etc/backup/syncthing.conf
    owner: root
    group: root
    mode:  0444
  tags: [backup]

- name: deploy backup service config
  copy:
    src:   backup/backup.service
    dest:  /etc/systemd/system/backup.service
    owner: root
    group: root
    mode:  0444
  tags: [backup]

- name: deploy backup service timer
  copy:
    src:   backup/backup.timer
    dest:  /etc/systemd/system/backup.timer
    owner: root
    group: root
    mode:  0444
  tags: [backup]

- name: reload systemd units
  systemd:
    daemon_reload: yes
  tags: [backup]

- name: enable backup timer
  systemd:
    name:    backup.timer
    state:   started
    enabled: yes
  tags: [backup]
