---

- name: set miniserv_role_path
  set_fact:
    miniserv_role_path: "{{ role_path }}"
  tags: [always]

- name: include local-infra vars
  include_vars: global/local-infra.yml
  tags: [always]

- name: include docker provision-time tasks
  include_role:
    name: server/lib/provision/docker

- name: include docker setup tasks
  include_tasks: docker.yml
  tags:
    - docker

- name: include secure web application gateway (swag) setup tasks
  include_tasks: swag.yml
  tags: [always]  # to configure the docker networks that swag shares with other services

- name: include syncthing setup role
  include_role:
    name: server/lib/provision/linuxserver-docker-service
    apply:
      tags: [syncthing]
  vars:
    service_name:   syncthing
    image_filename: "{{ metadata_dir }}/syncthing-docker-image"
    user:
      name: syncthing
      uid:  "{{ syncthing_uid }}"
    group:
      name: syncthing
      gid: "{{ syncthing_gid }}"
    directories:
      - "{{ syncthing_data_dir }}"
      - "{{ syncthing_data_dir }}/config"
      - "{{ syncthing_data_dir }}/data"
    published_ports:
      - "127.0.0.1:8384:8384"
      - "22000:22000"
      - "21027:21027/udp"
    volumes:
      - "{{ syncthing_data_dir }}/config:/config"
      - "{{ syncthing_data_dir }}/data:/data"
  tags:
    - syncthing

- name: include unifi setup role
  include_role:
    name: server/lib/provision/linuxserver-docker-service
    apply:
      tags: [unifi]
  vars:
    service_name:   unifi
    image_filename: "{{ metadata_dir }}/unifi-docker-image"
    user:
      name: unifi
      uid:  "{{ unifi_uid }}"
    group:
      name: unifi
      gid: "{{ unifi_gid }}"
    directories:
      - "{{ unifi_data_dir }}/config:/config"
    networks:
      - name: bridge
      - name: swag_unifi
    published_ports:
      - "3478:3478/udp"
      - "6789:6789"
      - "8080:8080"
      - "8081:8081"
      - "10001:10001/udp"
    volumes:
      - "{{ unifi_data_dir }}/config:/config"
  tags:
    - unifi

- name: include pi-hole setup tasks
  include_tasks: pi-hole.yml
  tags:
    - pi-hole

- name: include air quality setup tasks
  include_tasks: air-quality.yml
  tags:
    - air-quality

- name: include vaultwarden setup tasks
  include_tasks: vaultwarden.yml
  tags:
    - vaultwarden
