---

- name: configure swag/vaultwarden network
  docker_network:
    name: swag_vaultwarden
  tags:
    - swag
    - vaultwarden

- name: include secure web application gateway (swag) setup role
  include_role:
    name: server/lib/provision/linuxserver-docker-service
    apply:
      tags: [swag]
  vars:
    service_name:   swag
    image_filename: "{{ metadata_dir }}/swag-docker-image"
    user:
      name: swag
      uid:  "{{ swag_uid }}"
    group:
      name: swag
      gid: "{{ swag_gid }}"
    capabilities:
      - NET_ADMIN

    # See https://github.com/linuxserver/docker-swag#parameters
    # for a description of these parameters.
    env:
      URL:        "{{ vaultwarden_domain }}"
      EMAIL:      letsencrypt@johnk.io
      VALIDATION: http
      STAGING:    "false"
    directories:
      - "{{ swag_data_dir }}/config"
    networks:
      - name: swag_vaultwarden
    published_ports:
      - "80:80"
      - "443:443"
    volumes:
      - "{{ swag_data_dir }}/config:/config"
  tags:
    - swag
