---

- name: configure swag/vaultwarden network
  docker_network:
    name: swag_vaultwarden
  tags:
    - swag
    - vaultwarden

- name: configure swag/unifi network
  docker_network:
    name: swag_unifi
  tags:
    - swag
    - unifi

- name: include secure web application gateway (swag) setup role
  include_role:
    name: server/lib/provision/linuxserver-docker-service
    apply:
      tags: [swag]
  vars:
    service_name:   swag
    image_filename: "{{ metadata_dir }}/swag-docker-image"
    user:
      name: swag
      uid:  "{{ swag_uid }}"
    group:
      name: swag
      gid: "{{ swag_gid }}"
    capabilities:
      - NET_ADMIN

    # See https://github.com/linuxserver/docker-swag#parameters
    # for a description of these parameters.
    env:
      URL:             johnk.io
      SUBDOMAINS:      "{{ miniserv_ssl_domains.values() | map('regex_replace', '\\..+$', '') | join(',') }}"
      ONLY_SUBDOMAINS: "true"
      EMAIL:           letsencrypt@johnk.io
      VALIDATION:      http
      STAGING:         "false"
    directories:
      - "{{ swag_data_dir }}/config"
    config:
      # The linuxserver-docker-service role tries to look up templates in its own templates directory.
      # To get around that, specify the full path to the vaultwarden template.
      - src:  "{{ miniserv_role_path }}/files/swag/nginx/vaultwarden.subdomain.conf"
        dest: "{{ swag_data_dir }}/config/nginx/proxy-confs/vaultwarden.subdomain.conf"

      - src:  "{{ miniserv_role_path }}/files/swag/nginx/unifi-controller.subdomain.conf"
        dest: "{{ swag_data_dir }}/config/nginx/proxy-confs/unifi-controller.subdomain.conf"

      - src:  "{{ miniserv_role_path }}/files/swag/nginx/default.conf"
        dest: "{{ swag_data_dir }}/config/nginx/site-confs/default.conf"

      - src:  "{{ miniserv_role_path }}/files/swag/fail2ban/vaultwarden-fail.conf"
        dest: "{{ swag_data_dir }}/config/fail2ban/filter.d/vaultwarden-fail.conf"

      - src:  "{{ miniserv_role_path }}/files/swag/fail2ban/jail.local"
        dest: "{{ swag_data_dir }}/config/fail2ban/jail.local"
    networks:
      - name: bridge
      - name: swag_unifi
      - name: swag_vaultwarden
    published_ports:
      - "80:80"
      - "443:443"
    volumes:
      - "{{ swag_data_dir }}/config:/config"
      - "{{ vaultwarden_data_dir }}/log:/vaultwarden-log:ro"
  tags:
    - swag
