---

- name: lookup persisted syncthing docker image
  shell:
    cmd: 'printf "$(< "$METADATA_FILE")"'
    executable: /bin/bash
  environment:
    METADATA_FILE: "{{ metadata_dir }}/syncthing-docker-image"
  register: syncthing_docker_image_lookup
  changed_when: false

- name: set syncthing_docker_image from lookup
  set_fact:
    syncthing_docker_image: "{{ syncthing_docker_image_lookup.stdout.rstrip() }}"

- name: create syncthing group
  group:
    name: syncthing
    gid:  "{{ syncthing_gid }}"

- name: create syncthing user
  user:
    name:    syncthing
    comment: syncthing service
    uid:     "{{ syncthing_uid }}"
    group:   syncthing
    shell:   "{{ nologin_shell }}"

- name: create syncthing directories
  file:
    path:  "{{ item }}"
    state: directory
    owner: syncthing
    group: syncthing
    mode:  0750
  with_items:
    - "{{ syncthing_data_dir }}"
    - "{{ syncthing_data_dir }}/config"
    - "{{ syncthing_data_dir }}/data"

- name: start syncthing container
  docker_container:
    name:       syncthing
    image:      "{{ syncthing_docker_image }}"
    log_driver: journald
    log_options:
      tag: syncthing
    env:
      PUID:      "{{ syncthing_uid | string }}"
      PGID:      "{{ syncthing_gid | string }}"
      UMASK_SET: "077"
      TZ:        America/Chicago
    published_ports:
      - "127.0.0.1:8384:8384"
      - "22000:22000"
      - "21027:21027/udp"
    volumes:
      - "{{ syncthing_data_dir }}/config:/config"
      - "{{ syncthing_data_dir }}/data:/data"
    restart_policy: unless-stopped
