---

- name: lookup vaultwarden docker image
  shell:
    cmd: 'printf "$(< "$DOCKER_IMAGE_FILE")"'
    executable: /bin/bash
  environment:
    DOCKER_IMAGE_FILE: "{{ metadata_dir }}/vaultwarden-docker-image"
  register: vaultwarden_image_lookup
  changed_when: false
  tags: [vaultwarden]

- name: set vaultwarden_docker_image from lookup
  set_fact:
    vaultwarden_docker_image: "{{ vaultwarden_image_lookup.stdout.rstrip() }}"
  tags: [vaultwarden]

- name: create vaultwarden group
  group:
    name: vaultwarden
    gid:  "{{ vaultwarden_gid }}"
  tags: [vaultwarden]

- name: create vaultwarden user
  user:
    name:    vaultwarden
    uid:     "{{ vaultwarden_uid }}"
    comment: vaultwarden service
    group:   vaultwarden
    shell:   "{{ nologin_shell }}"
  tags: [vaultwarden]

- name: create vaultwarden data directory
  file:
    path:  "{{ vaultwarden_data_dir }}"
    state: directory
    owner: root
    group: vaultwarden
    mode:  0770
  tags: [vaultwarden]

- name: configure vaultwarden backup
  copy:
    content: |
      VAULTWARDEN_CONTAINER=vaultwarden
      VAULTWARDEN_DATA_DIR={{ vaultwarden_data_dir | quote }}
      VAULTWARDEN_SYNCTHING_DIR={{ [syncthing_data_dir, 'data', 'vaultwarden'] | path_join | quote }}
    dest: /etc/vaultwarden-backup.conf
    owner: root
    group: root
    mode:  "0444"
  tags: [vaultwarden]

- name: deploy vaultwarden backup script
  copy:
    src:   vaultwarden-backup
    dest:  /usr/local/bin/vaultwarden-backup
    owner: root
    group: root
    mode:  0555
  tags: [vaultwarden]

- name: deploy vaultwarden-backup systemd service
  copy:
    src:   vaultwarden-backup.service
    dest:  /etc/systemd/system/vaultwarden-backup.service
    owner: root
    group: root
    mode:  0444
  tags: [vaultwarden]

- name: deploy vaultwarden-backup systemd timer
  copy:
    src:   vaultwarden-backup.timer
    dest:  /etc/systemd/system/vaultwarden-backup.timer
    owner: root
    group: root
    mode:  0444
  tags: [vaultwarden]

- name: reload systemd units
  systemd:
    daemon_reload: yes
  tags: [vaultwarden]

- name: enable vaultwarden-backup timer
  systemd:
    name:    vaultwarden-backup.timer
    state:   started
    enabled: yes
  tags: [vaultwarden]

- name: start vaultwarden container
  docker_container:
    name:       "vaultwarden"
    image:      "{{ vaultwarden_docker_image }}"
    log_driver: journald
    log_options:
      tag: vaultwarden
    env:
      # Credential used to log into the admin page.
      # If this is unset, the admin page is disabled.
      #
      # ADMIN_TOKEN: "{{ lookup('pipe', 'base64 /dev/urandom | head -c64') }}"

      DOMAIN: "https://{{ vaultwarden_domain }}"

      # We have to make the port a non-privileged port because we're running as
      # an unprivileged user.
      ROCKET_PORT:        "8080"
      SIGNUPS_ALLOWED:    "false"
      SHOW_PASSWORD_HINT: "false"
      WEBSOCKET_ENABLED:  "true"
    networks:
      - name: bridge
      - name: swag_vaultwarden
    security_opts:
      - "seccomp:unconfined"
    published_ports:
      - "{{ vaultwarden_port }}:8080"
    volumes:
      - "{{ vaultwarden_data_dir }}:/data"
    user: "{{ vaultwarden_uid }}:{{ vaultwarden_gid }}"
    restart_policy: unless-stopped
  tags: [vaultwarden]
