#!/bin/bash

wireguard_cache_dir={{ wireguard_cache_dir | quote }}
wireguard_pkg_url={{ wireguard_package.url | quote }}
wireguard_pkg_dest={{ wireguard_package.dest | quote }}
wireguard_expected_checksum={{ wireguard_package.checksum | quote }}

mkdir -p "$wireguard_cache_dir"
chown root:root "$wireguard_cache_dir"
chmod 0755 "$wireguard_cache_dir"

if ! [[ -f "$wireguard_pkg_dest" ]]; then
    curl -s -L "$wireguard_package_url" > "$wireguard_pkg_dest"
fi

wireguard_checksum=$(shasum -a 512 "$wireguard_pkg_dest" | awk '{ print $1 }')

if [[ "$wireguard_checksum" != "$wireguard_expected_checksum" ]]; then
    printf 'bad checksum for wireguard package\n' >&2
    printf 'got checksum:      %s\n' "$wireguard_checksum" >&2
    printf 'expected checksum: %s\n' "$wireguard_expected_checksum" >&2
    exit 1
fi

if ! lsmod | grep -q wireguard; then
    dpkg -i "$wireguard_pkg_dest"
    sudo modprobe wireguard
fi
