#!/bin/bash

# dev or prod
env="$1"

if ! [[ "$env" =~ ^(dev|prod)$ ]]; then
    echo "usage: $0 [dev|prod]" >&2
    exit 1
fi
script_dir="$(realpath "$(dirname "$0")")"

account_id="$(aws sts get-caller-identity --output text | awk '{ print $1 }')"

deploy_tmpdir="$(mktemp --tmpdir -d aws-dyndns-deploy.XXXXXX)"
if [[ -z "$deploy_tmpdir" ]]; then
    echo 'Failed creating temporary directory' >&2
    exit 2
fi
function cleanup() {
    [[ -n "$deploy_tmpdir" ]] && rm -rf "$deploy_tmpdir"
}
trap cleanup EXIT

zip -j "$deploy_tmpdir/dyndns.zip" "$script_dir/dyndns.py"
aws lambda update-function-code --function-name "dyndns-${env}" --zip-file "fileb://$deploy_tmpdir/dyndns.zip"
