#!/bin/bash

env=$1

function cleanup() {
    [[ -n "$deploy_tmpdir" ]] && rm -rf "$deploy_tmpdir"
}

if ! [[ "$env" =~ ^(dev|prod)$ ]]; then
    echo "usage: $0 [dev|prod]" >&2
    exit 1
fi

script_dir="$(realpath "$(dirname "$0")")"
deploy_tmpdir="$(mktemp --tmpdir -d aws-dyndns-deploy.XXXXXX)"
if [[ -z "$deploy_tmpdir" ]]; then
    echo 'Failed creating temporary directory' >&2
    exit 2
fi
trap cleanup EXIT

zip -j "$deploy_tmpdir/dyndns.zip" "$script_dir/dyndns.py"
aws --no-cli-pager lambda update-function-code \
    --function-name "dyndns-${env}" \
    --zip-file "fileb://$deploy_tmpdir/dyndns.zip"
