---

edgeos_ansible_cfg: /config/config.ansible
network_subnet: 192.168.192.0/20
pihole_ip: 192.168.192.10
router_ip: 192.168.192.1

dyndns_hostname:  "{{ lookup('aws_ssm', '/' + server_env + '/dyndns/hostname') }}"
dyndns_url:       "{{ lookup('aws_ssm', '/' + server_env + '/dyndns/url') }}"
dyndns_username:  "{{ lookup('aws_ssm', '/' + server_env + '/dyndns/creds/home/username') }}"
dyndns_password:  "{{ lookup('aws_ssm', '/' + server_env + '/dyndns/creds/home/password') }}"
dyndns_wan_iface: pppoe0

wireguard_cache_dir: /var/cache/wireguard
wireguard_config_dir: /config/wireguard
wireguard_package:
  dest:     "{{ wireguard_cache_dir }}/wireguard.deb"
  url:      https://github.com/WireGuard/wireguard-vyatta-ubnt/releases/download/1.0.20220627-1/e300-v2-v1.0.20220627-v1.0.20210914.deb
  checksum: 1e24168bc31f492906a834fdb959e5f672798de723e058890a3ae14aa20179c49fb06c793250fb216783d3d56226303e14b81337affd10958cc3cfd220f1a4d8
wireguard_server_ip: "192.168.222.1/24"
wireguard_listen_port: 51820

wireguard_peers:
  - name: johnk
    public_key: "eFWVoa6tdVREtOp+XV2NSHfX//iRBEJavFmRYjr0u2Y="
    ip_address: "192.168.222.10"

upstream_dns:
  - 208.67.222.222
  - 208.67.220.220

static_dhcp:
  - name: miniserv
    mac:  dc:a6:32:61:15:93
    ip:   "{{ pihole_ip }}"
    dns: "{{ ['miniserv.lan'] + (miniserv_ssl_domains.values() | list) }}"

  - name: ap-1f
    mac:  f4:92:bf:69:86:68
    ip:   192.168.192.11
    dns:
      - ap1f.lan

  - name: ap-3f
    mac:  f0:9f:c2:33:6b:76
    ip:   192.168.192.13
    dns:
      - ap3f.lan

  - name: switch0
    mac:  74:83:c2:0d:0a:4a
    ip:   192.168.192.2
    dns:
      - switch0.lan

  - name: johnk-desktop
    mac:  d8:bb:c1:10:03:e9
    ip:   192.168.193.50
    dns:
      - johnk-desktop.lan

  - name: media-center-pc
    mac:  d0:50:99:95:7c:53
    ip:   192.168.193.100
    dns:
      - media-center-pc.lan

  - name: dance-station
    mac:  4c:ed:fb:bf:ac:0e
    ip:   192.168.193.101
    dns:
      - dance-station.lan

  - name: val-desktop
    mac:  f0:9f:c2:33:6b:76
    ip:   192.168.193.200
    dns:
      - val-desktop.lan

  - name: val-phone-5ghz
    mac:  be:4f:e0:09:f1:fa
    ip:   192.168.193.201

  - name: val-phone-24ghz
    mac:  1a:54:6f:b8:a6:f6
    ip:   192.168.193.202

  - name: office-laserjet-pro
    mac:  e8:d8:d1:b0:f6:56
    ip:   192.168.193.10
    dns:
      - office-laserjet-pro.lan

  - name: gaming-rpi
    mac: e4:5f:01:09:b9:64
    ip:  192.168.193.102
    dns:
      - gaming-rpi.lan

  # Devices that are bad network citizens should be put into
  # 192.168.201.0/24. Smart TVs specifically are known not to obey
  # DNS settings offered by DHCP.
  - name: roku-family-room
    mac:  b8:3e:59:15:97:c8
    ip:   192.168.201.10

  - name: roku-living-room
    mac:  5c:ad:76:bd:c1:6d
    ip:   192.168.201.20

  - name: roku-master-bedroom
    mac:  5c:ad:76:89:06:c5
    ip:   192.168.201.30

static_dns:
  - ip: "{{ router_ip }}"
    dns:
      - router0.lan
      - vpn.johnk.io

  - ip: 172.17.17.17
    dns:
      - modem.lan

port_forwards: []
