---

edgeos_ansible_cfg: /config/config.ansible
network_subnet: 10.0.0.0/16
pi_hole_ip: 10.0.0.10
router_ip: 10.0.0.1

dyndns_hostname:  "{{ lookup('aws_ssm', '/' + server_env + '/dyndns/hostname') }}"
dyndns_url:       "{{ lookup('aws_ssm', '/' + server_env + '/dyndns/url') }}"
dyndns_username:  "{{ lookup('aws_ssm', '/' + server_env + '/dyndns/creds/home/username') }}"
dyndns_password:  "{{ lookup('aws_ssm', '/' + server_env + '/dyndns/creds/home/password') }}"
dyndns_wan_iface: pppoe0

upstream_dns:
  - 8.8.8.8
  - 8.8.4.4

static_dhcp:
  - name: ap0
    mac:  f0:9f:c2:33:6b:76
    ip:   10.0.0.8
    dns:
      - ap0.lan

  - name: johnk-desktop
    mac:  d0:50:99:95:7c:53
    ip:   10.0.0.50
    dns:
      - johnk-desktop.lan

  - name: val-desktop
    mac:  f0:9f:c2:33:6b:76
    ip:   10.0.0.60
    dns:
      - val-desktop.lan

static_dns:
  - ip: "{{ router_ip }}"
    dns:
      - router0.lan

  - ip: 10.0.0.10
    dns:
      - miniserv.johnk.io
      - syncthing.johnk.io
      - unifi.johnk.io

  - ip: 172.17.17.17
    dns:
      - modem.lan
