---

server_aws_user_data: "{{ ansible_ec2_user_data | from_json }}"
server_aws_asg:       "{{ server_aws_user_data.get('asg_name', None) }}"
server_category:      "{{ server_aws_user_data.get('category', None) }}"
server_dns:           "{{ server_aws_user_data.get('dns', None) }}"
server_env:           "{{ server_aws_user_data.get('env', None) }}"
server_extra:         "{{ server_aws_user_data.get('extra', None) }}"  # a validation task will make sure this is a dict
server_id:            "{{ ansible_ec2_instance_identity_document_instanceid }}"
server_model:         "{{ ansible_ec2_instance_type }}"
server_name:          "{{ server_aws_user_data.get('name', None) }}"
