---

- name: ensure required configuration variables are set
  assert:
    that:
      - "{{ item }} is defined and {{ item }} != ''"
  with_items:
    - centurylink_pppoe_username
    - centurylink_pppoe_password
    - network_subnet
    - router_ip
    - server_admin_comment
    - server_admin_username
    - server_admin_password
    - server_admin_ssh_pubkey
  tags: [always]

- name: deploy edgeos configuration
  include_role:
    name: network/lib/provision/edgeos-template
  vars:
    src:   config.j2
    dest:  /config/config.ansible
    owner: root
    group: vyattacfg
    mode:  "0640"

- name: load edgeos config
  edgeos_command:
    commands:
      - "configure"
      - "load {{ edgeos_ansible_cfg | quote }}"
      - "commit"

- name: confirm running config is ok
  pause:
    prompt: "Ensure router running config is OK; try logging in"

- name: save edgeos config
  edgeos_command:
    commands:
      - "configure"
      - "save"
