---

- name: ensure required configuration variables are set
  assert:
    that:
      - "item.value is defined and item.value not in ['', none]"
  with_items:
    - name:  centurylink_pppoe_username
      value: "{{ centurylink_pppoe_username }}"

    - name:  centurylink_pppoe_password
      value: "{{ centurylink_pppoe_password }}"

    - name:  network_subnet
      value: "{{ network_subnet }}"

    - name:  router_ip
      value: "{{ router_ip }}"

    - name:  server_admin_comment
      value: "{{ server_admin_comment }}"

    - name:  server_admin_username
      value: "{{ server_admin_username }}"

    - name:  server_admin_password
      value: "{{ server_admin_password }}"

    - name:  server_admin_ssh_pubkey
      value: "{{ server_admin_ssh_pubkey }}"

    - name:  wireguard_private_key
      value: "{{ wireguard_private_key }}"
  tags: [always]

# When specifying Ansible variables via -e, the value itself has to be quoted,
# apart from any quoting required by the shell. That's sort of confusing, so
# here we add an additional check that the value is passed correctly as a reminder.
- name: ensure server_admin_ssh_pubkey has two parts
  assert:
    that:
      - "(server_admin_ssh_pubkey.split(' ') | length) == 2"
    fail_msg: |
      server_admin_ssh_pubkey = '{{ server_admin_ssh_pubkey }}'
      ansible values with whitespace passed via `-e` must be quoted, e.g.
      -e 'server_admin_ssh_pubkey="ssh-rsa ..."'
  tags: [always]

- name: create requisite directories for config
  edgeos_command:
    commands:
      - "sudo mkdir -p {{ item | quote }}"
      - "sudo chown root:vyattacfg {{ item | quote }}"
      - "sudo chmod 0775 {{ item | quote }}"
  with_items:
    - /config/user-data
    - /config/user-data/ipsets
    - /config/scripts
    - /config/scripts/post-config.d
    - /config/wireguard

- name: deploy wireguard private key
  edgeos_command:
    commands:
      - 'printf "%s\n" {{ wireguard_private_key | quote }} > /config/wireguard/wg.key'

# This needs to execute here because it includes "role_path".
#
# If we put it into vars/main.yml, the path will be determined
# in the context of the of the edgeos-template role. Yes, it's
# dumb.
- name: configure USA IPv4 ranges
  set_fact:
    usa_ipv4_ranges: "{{ lookup('file', role_path + '/files/usa-ipv4-ranges.txt') | split('\n') | reject('match', '^\\s*#') }}"

- name: deploy edgeos configuration
  include_role:
    name: network/lib/provision/edgeos-template
  vars:
    src:   config.j2
    dest:  /config/config.ansible
    owner: root
    group: vyattacfg
    mode:  "0640"

- name: deploy USA IPv4 ipset template
  include_role:
    name: network/lib/provision/edgeos-template
  vars:
    src:   saved-ipset.j2
    dest:  /config/user-data/ipsets/usa-ipv4-ranges.ipset
    owner: root
    group: vyattacfg
    mode:  "0644"
    ipset_name:    usa-ipv4
    ipset_family:  inet
    ipset_entries: "{{ usa_ipv4_ranges }}"

- name: deploy ipset restore script
  include_role:
    name: network/lib/provision/edgeos-template
  vars:
    src:   restore-ipsets
    dest:  /config/scripts/post-config.d/restore-ipsets
    owner: root
    group: vyattacfg
    mode:  "0755"

- name: load edgeos config
  edgeos_command:
    commands:
      - "configure"
      - "load {{ edgeos_ansible_cfg | quote }}"
      - "commit"
      - 'for i in /config/scripts/post-config.d/*; do sudo "$i"; done'

- name: confirm running config is ok
  pause:
    prompt: "Ensure router running config is OK; try logging in"

- name: save edgeos config
  edgeos_command:
    commands:
      - "configure"
      - "save"
