---

- name: ensure required configuration variables are set
  assert:
    that:
      - "{{ item }} is defined and {{ item }} != ''"
  with_items:
    - dyndns_hostname
    - dyndns_password
    - dyndns_url
    - dyndns_username
    - dyndns_wan_iface
  tags: [always, dyndns]

- name: deploy dyndns configuration
  include_role:
    name: network/lib/provision/edgeos-template
    apply:
      tags: [dyndns]
  vars:
    src:   dyndns-cfg.j2
    dest:  /config/user-data/dyndns/cfg
    owner: root
    group: vyattacfg
    mode:  "0640"
  tags: [dyndns]

- name: deploy dyndns script
  include_role:
    name: network/lib/provision/edgeos-template
    apply:
      tags: [dyndns]
  vars:
    src:   dyndns.sh
    dest:  /config/user-data/dyndns/dyndns.sh
    owner: root
    group: root
    mode:  "0555"
  tags: [dyndns]
