---

- name: include local-infra vars
  include_vars: global/local-infra.yml
  tags: [always]

- name: include router dyndns configuration tasks
  include_tasks: dyndns.yml
  tags: [dyndns]

- name: install wireguard
  include_tasks:
    file: wireguard.yml
    apply:
      tags: [wireguard]
  tags: [wireguard]

- name: include router configuration tasks
  include_tasks: config.yml
  tags: [config]
