---

- name: deploy wireguard install script
  include_role:
    name: network/lib/provision/edgeos-template
  vars:
    src:   install-wireguard
    dest:  /config/scripts/install-wireguard
    owner: root
    group: vyattacfg
    mode:  "0755"

- name: install wireguard
  edgeos_command:
    commands:
      - sudo /config/scripts/install-wireguard
