#!/bin/bash

###############
# run-linters #
###############
#
# run-linters runs the linters for this project.

set -o pipefail

script_path=$(readlink -f "$0")
script_dir=$(dirname "$script_path")

if [[ "$IN_INFRA_DEPLOY_VIRTUALENV" != 1 ]]; then
	exec "${script_dir}/with-venv" "$0" "$@"
fi

cd "$script_dir"

source 'lib.sh'
errorable mypy --strict .
errorable ruff check .

exit "$final_rc"
