#!/bin/bash

# Ansible variables are set in /etc/metadata,
# which is populated by EC2 userdata.
source /etc/metadata
cd /opt/cloud-tools/ansible
ansible-playbook -i localhost, \
    -e instance_category="$INSTANCE_CATEGORY" \
    -e instance_class="$INSTANCE_CLASS" \
    -e instance_env="$INSTANCE_ENV" \
    -e instance_name="$INSTANCE_NAME" \
    provision-ec2.yml
