---

##########################
# vars/global/global.yml #
##########################

# Provides the value of infra_revision when provisioning against physical infrastructure.
# The packer/build script will provide this to Ansible via the --extra-vars argument.
infra_revision: "{{ lookup('pipe', 'cd ' + (playbook_dir | quote) + '/../..; ./revision') }}"

# The AWS region that is used to look up SSM parameters.
ssm_lookup_region: "{{ ansible_ec2_placement_region if ansible_ec2_placement_region is defined else 'us-east-1' }}"
