---

###############################
# vars/global/local-infra.yml #
###############################

# The first entry here will be the primary name
# on the issued certificate.
miniserv_ssl_domains:
  miniserv:    miniserv.johnk.io
  pihole:      pihole.johnk.io
  syncthing:   syncthing.johnk.io
  unifi:       unifi.johnk.io
  vaultwarden: vaultwarden.johnk.io
