"""
Global test configuration for backup tests.
"""

from pathlib import Path
import shutil
from tempfile import mkdtemp
from typing import Generator

import pytest

from testlib import (
    BackupSourceInfo,
    BackupSourceSubdirectory,
    DataGenerator,
    MockCommandExecutor,
)


@pytest.fixture
def backup_src_info(datagen: DataGenerator) -> BackupSourceInfo:
    """
    Backup source directory containing generated data.
    """
    backup_src_root = Path("backup-src")
    D = BackupSourceSubdirectory

    data_dirs = [
        D(Path("0001"), 128, 256),
        D(Path("0002"), 512, 128),
        D(Path("0003"), 8, 2048),
    ]

    bsi = BackupSourceInfo(datagen.root / backup_src_root)

    for dd in data_dirs:
        bsi.directories.append(dd)
        datagen.generate_random(backup_src_root / dd.path, dd.count, dd.file_size)

    return bsi


@pytest.fixture
def datagen_dir(tmpdir: Path) -> Path:
    """
    Path to the root directory containing data generated by the datagen fixture.
    """
    return tmpdir / "datagen"


@pytest.fixture
def datagen(datagen_dir: Path) -> DataGenerator:
    """
    Object that can generate data for backup integration test runs.
    """
    return DataGenerator(datagen_dir)


@pytest.fixture
def mock_cmd_executor() -> MockCommandExecutor:
    """
    Mock command executor. Commands are not actually executed using this executor.
    """
    return MockCommandExecutor()


@pytest.fixture
def tmpdir() -> Generator[Path]:
    """
    Temporary directory that tests can use to store data.
    """
    d = Path(mkdtemp(prefix="backupjob-tests-"))

    yield d

    shutil.rmtree(d, ignore_errors=True)
