"""
Global test configuration for backup tests.
"""

from pathlib import Path
import shutil
from tempfile import mkdtemp
from typing import Generator

import pytest

from testlib import DataGenerator, MockCommandExecutor


@pytest.fixture
def datagen_dir(tmpdir: Path) -> Path:
    """
    Path to the root directory containing data generated by the datagen fixture.
    """
    return tmpdir / "datagen"


@pytest.fixture
def datagen(datagen_dir: Path) -> DataGenerator:
    """
    Object that can generate data for backup integration test runs.
    """
    return DataGenerator(datagen_dir)


@pytest.fixture
def mock_cmd_executor() -> MockCommandExecutor:
    """
    Mock command executor. Commands are not actually executed using this executor.
    """
    return MockCommandExecutor()


@pytest.fixture
def tmpdir() -> Generator[Path]:
    """
    Temporary directory that tests can use to store data.
    """
    d = Path(mkdtemp(prefix="backupjob-tests-"))

    yield d

    shutil.rmtree(d, ignore_errors=True)
