#!/bin/bash

script_dir="$(dirname "$0")"
function run_docker() {
    local test_image='debian:cloud-tools-test-9'
    local test_cmd=()
    local cloudtools_dir='/opt/cloudtools'
    local volpath="$(readlink -f "$script_dir/../..")"

    cd "$script_dir"
    docker build -t "$test_image" .
    set -x
    docker run -e IN_DOCKER=1 \
        -w "$cloudtools_dir/ansible" \
        -v "$volpath:$cloudtools_dir" \
        -t "$test_image" \
        'test/runtest'
    set +x
}

function run_test() {
    set -x
    ansible-playbook -i localhost, -e local_testing=true provision-ec2.yml
    set +x
}

if [[ "$IN_DOCKER" == '1' ]]; then
    run_test
else
    run_docker
fi
