---

- name: deploy srvtools
  hosts: all
  become: yes
  tasks:
    - name: include srvtools deployment tasks
      include_role:
        name: server/lib/build/core
        tasks_from: srvtools.yml
