---

- name: provision router
  hosts: router0.lan
  become: no
  gather_facts: no

  pre_tasks:
    - name: include global variables
      include_vars: global/global.yml
      tags: [always]

    - name: include server admin variables
      include_vars: global/server-admin.yml
      tags: [always]

  roles:
      - network/role/provision/router
