---

# This playbook is performed at build-time to install software
# on a server. In AWS, this helps build an AMI.
#
# Configuration should be performed by server-provision.yml.

- import_playbook: server-setup.yml
  vars:
    server_setup_phase: build
