Vagrant.configure("2") do |config|
  # Requirements to use this Vagrantfile:
  #
  # 1. Install necessary software:
  #   * libvirt
  #   * ebtables
  #   * dnsmasq
  #
  # 2. Install vagrant libvirt plugin: `vagrant plugin install vagrant-libvirt`
  #
  # 3. Start libvirtd service
  config.vm.box = "debian/stretch64"
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provider "libvirt" do |vm|
    vm.memory = 1024
    vm.cpus = 2
  end
end

# vim: ft=ruby
