#!/bin/bash

# This is the data directory that Vaultwarden uses normally.
if [[ -z "$VAULTWARDEN_DATA_DIR" ]]; then
    echo 'error: expected VAULTWARDEN_DATA_DIR to be specified via environment' >&2
    exit 10
fi

# This is the Syncthing directory containing Vaultwarden data to be sync'd for
# cloud backup.
if [[ -z "$VAULTWARDEN_SYNCTHING_DIR" ]]; then
    echo 'error: expected VAULTWARDEN_SYNCTHING_DIR to be specified via environment' >&2
    exit 11
fi

if [[ -z "$VAULTWARDEN_CONTAINER" ]]; then
    echo 'error: expected VAULTWARDEN_CONTAINER to be specified via environment' >&2
    exit 12
fi

docker stop "$VAULTWARDEN_CONTAINER" >&2
if [[ "$?" != 0 ]]; then
    echo "error: failed stopping $VAULTWARDEN_CONTAINER container; attempting to continue with backup anyway" >&2
else
    echo "stopped $VAULTWARDEN_CONTAINER" >&2
fi
rsync -rltv --delete "$VAULTWARDEN_DATA_DIR/" "$VAULTWARDEN_SYNCTHING_DIR/data"
chown -R syncthing:syncthing "$VAULTWARDEN_SYNCTHING_DIR"
docker start "$VAULTWARDEN_CONTAINER" >&2
if [[ "$?" != 0 ]]; then
    echo "error: failed restarting $VAULTWARDEN_CONTAINER container" >&2
    exit 13
else
    echo "restarted $VAULTWARDEN_CONTAINER" >&2
fi
